# Generated by Django 4.0.5 on 2023-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
