# Generated by Django 4.0.5 on 2023-02-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
